version: '3.9'
services:
  dev:
    container_name: sf-tech
    image: server-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: yarn start:debug
    ports:
      - 3001:3001
      - 9229:9229
    networks:
      - server-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      MONGO_URL: process.env.DATABASE_URL

  mongodb:
    image: mongo:5.0.0
    container_name: sf-tech
    environment:  
      - MONGO_INITDB_ROOT_USERNAME=<process.env.MONGODB_USER>
      - MONGO_INITDB_ROOT_PASSWORD=<process.env.MONGODB_PASSWORD>
    networks:
      - server-network
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
networks:
  server-network: