version: '3.9'

services:
  database:
    image: postgres:latest # Corrigido o nome da imagem do PostgreSQL
    container_name: sf-tech-postgresql
    ports:
      - '5432:5432' # Alterado para usar strings para as portas
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data # Corrigido o caminho do volume
    restart: always
    networks:
      - postgresql-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379' # Alterado para usar strings para as portas
    volumes:
      - ./redis-data:/data
    command: redis-server
    restart: always
    networks:
      - postgresql-network # Alterado o nome da rede para corresponder à rede do PostgreSQL

  app:
    build: .
    container_name: sf-tech
    ports:
      - '3003:3003' # Alterado para usar strings para as portas
    networks:
      - postgresql-network
    depends_on:
      - database
      - redis
    restart: always
    env_file:
      - .env
    volumes:
      - ./redis.crt:/usr/src/redis.crt

volumes:
  postgresql-data: # Corrigido o nome do volume
    driver: local
  redis-data:
    driver: local

networks:
  postgresql-network: # Corrigido o nome da rede
    driver: bridge
