version: '3.9'

services:
  database:
    image: postgres:latest
    container_name: sf-tech-postgresql
    ports:
      - 5432:5432
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
    restart: always
    networks:
      - postgresql-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
    command: redis-server
    restart: always
    networks:
      - postgresql-network #

  app:
    build: .
    container_name: sf-tech
    ports:
      - 3003:3003
    networks:
      - postgresql-network
    depends_on:
      - database
      - redis
    restart: always
    env_file:
      - .env
    volumes:
      - ./redis.crt:/usr/src/redis.crt

volumes:
  postgresql-data:
    driver: local
  redis-data:
    driver: local

networks:
  postgresql-network:
    driver: bridge
