export enum ProductType {
  COMPUTER = 'COMPUTER',
  NOTEBOOK = 'NOTEBOOK',
  CELL = 'CELL',
  MOUSE = 'MOUSE',
  KEYBOARD = 'KEYBOARD',
  SOUND_PHONE = 'SOUND_PHONE',
  PRINTER = 'PRINTER',
  MONITOR = 'MONITOR',
  PERIPHERAL = 'PERIPHERAL',
  USB = 'USB',
  OTHERS = 'OTHERS',
}
